name: Build & Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@master
      with:
        submodules: 'recursive'

    - name: Build
      uses: ./

    - name: Release
      if: always()
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: v0.1.0-alpha
        file: '*/*/*.pdf'
        file_glob: true
        overwrite: true

# vim: ts=2 sw=2
